name       : ansible
version    : 2.3.0.0
release    : 4
source     :
    - http://releases.ansible.com/ansible/ansible-2.3.0.0.tar.gz : 299f3907cd566a20e163942fa82b6afc86ef89c2726ba503b90c1a651e82a458
license    : GPL-3.0
component  : system.utils
summary    : Ansible is a radically simple IT automation system
description: |
    Ansible is a radically simple IT automation system
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - python-jinja
build      : |
    %python3_setup
install    : |
    %python3_install
