name       : ansible
version    : 2.2.1.0
release    : 3
source     :
    - http://releases.ansible.com/ansible/ansible-2.2.1.0.tar.gz : 63a12ea784c0f90e43293b973d5c75263634c7415e463352846cd676c188e93f
license    : GPL-3.0
component  : system.utils
summary    : Ansible is a radically simple IT automation system
description: |
    Ansible is a radically simple IT automation system
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - python-jinja
build      : |
    %python3_setup
install    : |
    %python3_install
