name       : ansible
version    : 2.15.3
release    : 39
source     :
    - https://github.com/ansible/ansible/archive/refs/tags/v2.15.3.tar.gz : 1ce23850aefcee176931d3f4f190af8c87461e63b90d0a84a3188d30a83343c2
license    : GPL-3.0-or-later
component  : system.utils
summary    : Ansible is a radically simple IT automation system
description: |
    Ansible is a radically simple IT automation system
builddeps  :
    - pkgconfig(python3)
    - asciidoc
    - python-docutils
    - python-jinja
rundeps    :
    - python-jinja
    - python-paramiko
    - python-resolvelib
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
