name       : ansible
version    : 2.4.0.0
release    : 7
source     :
    - https://github.com/ansible/ansible/archive/v2.4.0.0-1.tar.gz : 9218b47f9f9ff9fbfb578c31850362e1232a1ee7c28fd936ff44a710f23f1195
license    : GPL-3.0
component  : system.utils
summary    : Ansible is a radically simple IT automation system
description: |
    Ansible is a radically simple IT automation system
builddeps  :
    - pkgconfig(python-3.5)
    - asciidoc
    - python-jinja
rundeps    :
    - python-jinja
    - python-paramiko
    - pyyaml
build      : |
    %python3_setup
    %make docs
install    : |
    %python3_install
    install -d $installdir/usr/share/man/man1
    install -Dm 00644 docs/man/man1/*.1 $installdir/usr/share/man/man1/
    install -Dm 00644 examples/ansible.cfg $installdir/etc/ansible/ansible.cfg
    install -Dm 00644 examples/hosts $installdir/etc/ansible/hosts
