name       : ansible
version    : 2.7.5
release    : 16
source     :
    - https://github.com/ansible/ansible/archive/v2.7.5.tar.gz : 6ef081c8ded1c9f0cf6368cde36b2f5b704e3940857818ad460dce1422aeb05e
license    : GPL-3.0-or-later
component  : system.utils
summary    : Ansible is a radically simple IT automation system
description: |
    Ansible is a radically simple IT automation system
builddeps  :
    - pkgconfig(python3)
    - asciidoc
    - python-docutils
    - python-jinja
    - python-setuptools
rundeps    :
    - python-jinja
    - python-paramiko
    - pyyaml
build      : |
    %python3_setup
    %make docs
install    : |
    %python3_install
    install -d $installdir/usr/share/man/man1
    install -Dm 00644 docs/man/man1/*.1 $installdir/usr/share/man/man1/
    install -Dm 00644 examples/ansible.cfg $installdir/etc/ansible/ansible.cfg
    install -Dm 00644 examples/hosts $installdir/etc/ansible/hosts
