name       : ansible
version    : 2.2.0.0
release    : 2
source     :
    - http://releases.ansible.com/ansible/ansible-2.2.0.0.tar.gz : d9f198d293394ce0f8ba802561b21368888e3301036a706b5584641b49408586
license    : GPL-3.0
component  : system.utils
summary    : Ansible is a radically simple IT automation system
description: |
    Ansible is a radically simple IT automation system
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - python-jinja
build      : |
    %python3_setup
install    : |
    %python3_install
