name       : ansible
version    : 2.10.4
release    : 23
source     :
    - https://github.com/ansible/ansible/archive/v2.10.4.tar.gz : 1d65835ab4c116e56bf4acedeac71219e35d6ebb58092a86845fb7c694bfe5c4
license    : GPL-3.0-or-later
component  : system.utils
summary    : Ansible is a radically simple IT automation system
description: |
    Ansible is a radically simple IT automation system
builddeps  :
    - pkgconfig(python3)
    - asciidoc
    - python-docutils
    - python-jinja
    - python-setuptools
rundeps    :
    - python-jinja
    - python-paramiko
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm 00644 examples/ansible.cfg $installdir/etc/ansible/ansible.cfg
    install -Dm 00644 examples/hosts $installdir/etc/ansible/hosts
