name       : ansible
version    : 2.5.1
release    : 11
source     :
    - https://github.com/ansible/ansible/archive/v2.5.1.tar.gz : aa99e8afef5b34c842672a0b58b94437ab7da16e2dd7bdbedae378241bef3a80
license    : GPL-3.0-or-later
component  : system.utils
summary    : Ansible is a radically simple IT automation system
description: |
    Ansible is a radically simple IT automation system
builddeps  :
    - pkgconfig(python-2.7)
    - asciidoc
    - python-jinja
    - python-setuptools
rundeps    :
    - python-jinja
    - python-paramiko
    - pyyaml
build      : |
    %python_setup
    %make docs
install    : |
    %python_install
    install -d $installdir/usr/share/man/man1
    install -Dm 00644 docs/man/man1/*.1 $installdir/usr/share/man/man1/
    install -Dm 00644 examples/ansible.cfg $installdir/etc/ansible/ansible.cfg
    install -Dm 00644 examples/hosts $installdir/etc/ansible/hosts
