name       : ansible
version    : 2.7.8
release    : 17
source     :
    - https://github.com/ansible/ansible/archive/v2.7.8.tar.gz : c67741cec421fd0efaaa10bb12eaca3b537d4a8201d74cc4873b5c8c19fd2856
license    : GPL-3.0-or-later
component  : system.utils
summary    : Ansible is a radically simple IT automation system
description: |
    Ansible is a radically simple IT automation system
builddeps  :
    - pkgconfig(python3)
    - asciidoc
    - python-docutils
    - python-jinja
    - python-setuptools
rundeps    :
    - python-jinja
    - python-paramiko
    - pyyaml
build      : |
    %python3_setup
    %make docs
install    : |
    %python3_install
    install -d $installdir/usr/share/man/man1
    install -Dm 00644 docs/man/man1/*.1 $installdir/usr/share/man/man1/
    install -Dm 00644 examples/ansible.cfg $installdir/etc/ansible/ansible.cfg
    install -Dm 00644 examples/hosts $installdir/etc/ansible/hosts
