name       : ansible
version    : 2.13.3
release    : 30
source     :
    - https://github.com/ansible/ansible/archive/refs/tags/v2.13.3.tar.gz : 76dbcf268df2385a3d7805879e540fe6ab7bf665b367124ee10bcab6b3fd2399
license    : GPL-3.0-or-later
component  : system.utils
summary    : Ansible is a radically simple IT automation system
description: |
    Ansible is a radically simple IT automation system
builddeps  :
    - pkgconfig(python3)
    - asciidoc
    - python-docutils
    - python-jinja
rundeps    :
    - python-jinja
    - python-paramiko
    - python-resolvelib
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm 00644 examples/ansible.cfg $installdir/etc/ansible/ansible.cfg
    install -Dm 00644 examples/hosts $installdir/etc/ansible/hosts
